# Generated by Django 5.2.17 on 2026-08-31 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_user_id', models.PositiveIntegerField(unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('avatar_type', models.CharField(blank=True, max_length=20)),
                ('synced_dt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
