# Generated by Django 5.2.17 on 2026-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avrdude_path', models.CharField(blank=True, help_text="Path to the avrdude executable. Leave blank to use 'avrdude' on $PATH.", max_length=500)),
                ('esptool_path', models.CharField(blank=True, help_text="Path to the esptool.py executable. Leave blank to use 'esptool.py' on $PATH.", max_length=500)),
                ('openocd_path', models.CharField(blank=True, help_text="Path to the openocd executable. Leave blank to use 'openocd' on $PATH.", max_length=500)),
                ('stm32cubeprogrammer_path', models.CharField(blank=True, help_text="Path to the STM32_Programmer_CLI executable. Leave blank to use 'STM32_Programmer_CLI' on $PATH.", max_length=500)),
            ],
            options={
                'verbose_name': 'Device settings',
                'verbose_name_plural': 'Device settings',
            },
        ),
    ]
