# Generated by Django 5.2.17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_devicesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesettings',
            name='esptool_path',
        ),
    ]
