# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_devicesettings_esptool_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='printer_name',
            field=models.CharField(
                blank=True,
                help_text="CUPS print queue name for the test docket printer, e.g. "
                          "'Printer_POS-80' (used as 'lp -d <printer_name> ...'). Leave blank "
                          "if no printer is configured on this device.",
                max_length=200,
            ),
        ),
    ]
