# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_devicesettings_printer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='device_details_url_stem',
            field=models.CharField(
                blank=True,
                help_text="Base URL this device prepends to a DUT's serial number to build the "
                          "device details link/QR code on the Test Docket, e.g. "
                          "'https://d.superlab.au/'.",
                max_length=500,
            ),
        ),
    ]
