# Generated by Django 5.2.17 on 2026-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_devicesettings_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicesettings",
            name="timezone",
            field=models.CharField(
                default="Australia/Melbourne",
                help_text="This device's local timezone, used to print the Test Docket's test-execution date/time in local time rather than UTC.",
                max_length=63,
            ),
        ),
    ]
