# Generated by Django 5.2.17 on 2026-08-31 06:58

import django.db.models.deletion
import test_suites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.PositiveIntegerField(unique=True)),
                ('sku', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('hw_version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('synced_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sku', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.PositiveIntegerField(unique=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('DRAFT', 'Draft')], max_length=10)),
                ('register_created_dt', models.DateTimeField()),
                ('package_file', models.FileField(blank=True, null=True, upload_to=test_suites.models.test_suite_package_upload_path)),
                ('package_fetched_dt', models.DateTimeField(blank=True, null=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='test_suites.design')),
            ],
            options={
                'ordering': ['design', '-version'],
            },
        ),
    ]
