# Generated by Django 5.2.17 on 2026-08-31 07:57

import test_suites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_suites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=test_suites.models.design_thumbnail_upload_path),
        ),
    ]
