# Generated by Django 5.2.17 on 2026-08-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_suites', '0002_design_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
