# Generated by Django 5.2.17 on 2026-09-11 03:09

import django.db.models.deletion
import test_suites.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_suites", "0003_design_client_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100)),
                ("started_dt", models.DateTimeField()),
                ("finished_dt", models.DateTimeField()),
                ("passed", models.BooleanField()),
                ("aborted", models.BooleanField(default=False)),
                ("report", models.JSONField()),
                ("docket_text", models.TextField(blank=True)),
                (
                    "docket_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=test_suites.models.docket_image_upload_path,
                    ),
                ),
                ("docket_printed_dt", models.DateTimeField(blank=True, null=True)),
                ("docket_print_error", models.TextField(blank=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="test_runs",
                        to="test_suites.testsuite",
                    ),
                ),
            ],
            options={
                "ordering": ["-finished_dt"],
            },
        ),
    ]
